### ISSUE TITLE
feature request: write to the top of file

### ISSUE THREAD

**Issue by pliablepixels** [pbakondy/filelogger#3]
Hi, thank you for your fabulous library.
I had a feature request for future consideration -- ability to write to the top of the file.
Justification:many logs would like to have the latest log at the top, especially when the log file grows.

**Comment by pbakondy** [comment]
Hi,

when you write a new message to the logfile, the lib will append this string to the end of the logfile.
It is a quick method: open, seek to end, write, close.

Putting a string to the front of the file would be a complex method. You can not simply write the string because it would overwrite the existing content.

One possible implementation: create new file, write string, open existing file, open, copy full content through a stream, close files, delete current one, rename new one.
Another way: open file, read full content to memory, write string, write previous content, close file.

I would not implement this method because it is slow and not efficient.

Rather than that I would suggest to apply a reverse method at displaying the content of the logfile:

``` js
content.split('\n').reverse().join('\n')
```

**Comment by pliablepixels** [comment]
Hello, that sounds fine. Thanks.
